Assignment 2
pesto-students/p13-nishant-naithani-ShaikMoAbdullah pull request #3
Opened 2023-08-05 17:49 UTC by ShaikMoAbdullah

- [x] Completed Poem Webpage task
- [ ] Completed Hometown Webpage task
- [ ] Completed Your Favorite Fan Webpage task
- [ ] Completed HTML Tables task
- [ ] Completed News Article Webpage task

2023-08-07 15:59 UTC, NishantNaithani commented
@ShaikMoAbdullah ,

Added comments.

Thanks

2023-08-07 16:08 UTC, NishantNaithani requested changes

2023-08-07 16:08 UTC, NishantNaithani commented on Week-1/assignment_2.1/index.html
Here always wrap your webpage content under a parent tag,
For e.g. `<main><p>......</p></main>`

And the expected result is different not matching with your result.

2023-08-07 16:08 UTC, NishantNaithani commented on Week-1/assignment_2.2/index.html
Here always wrap your webpage content under a parent tag,
For e.g. `<main><p>......</p></main>`

2023-08-07 17:38 UTC, ShaikMoAbdullah commented on Week-1/assignment_2.1/index.html
Okay. I didn't know it should look exactly the same. I missed this line, `Maintain the correct formatting` given in the LMS. 

Will make the required changes.

2023-08-07 17:38 UTC, ShaikMoAbdullah commented on Week-1/assignment_2.2/index.html
Will make the required changes

2023-08-07 17:56 UTC, ShaikMoAbdullah commented
Made the required changes

Thanks

2023-08-08 16:16 UTC, NishantNaithani approved these changes

2023-08-08 18:45 UTC, merged