Week 3
pesto-students/p13-nishant-naithani-ShaikMoAbdullah pull request #6
Opened 2023-08-24 05:19 UTC by ShaikMoAbdullah

- [x] Completed all the week 3 assignments

2023-08-30 09:55 UTC, NishantNaithani requested changes

2023-08-30 09:55 UTC, NishantNaithani commented on Week-3/assignment-4.5/index.html
Here,
1. please use defined tags for the `text` type pf content.
2. class names should be meaningful.

2023-08-30 09:55 UTC, NishantNaithani commented on Week-3/assignment-5.2/index.html
Here,
1. under `body` tag we have added many tags for different purposes, but can be merged.

2023-08-30 09:55 UTC, NishantNaithani commented
Added comments

2023-08-30 15:41 UTC, ShaikMoAbdullah commented on Week-3/assignment-5.2/index.html
These tags were given in the template in LMS and we had to only make the required changes to achieve the desired UI result

2023-08-30 15:42 UTC, ShaikMoAbdullah commented on Week-3/assignment-4.5/index.html
Noted and made all the required changes.

2023-09-12 16:47 UTC, NishantNaithani approved these changes

2023-09-13 19:51 UTC, merged