Week 4
pesto-students/p13-nishant-naithani-ShaikMoAbdullah pull request #7
Opened 2023-09-08 01:31 UTC by ShaikMoAbdullah

- [x] Completed all week 4 assignments

2023-09-12 06:59 UTC, NishantNaithani requested changes

2023-09-12 06:59 UTC, NishantNaithani commented on Week-4/assignment-6.3/script.js
Here,
This will fail when I pass `PASSWORD` word having atleast 1 uppercase char.

2023-09-12 06:59 UTC, NishantNaithani commented on Week-4/assignment-8.2/script.js
Here,
Getting this as an answer
```javascript
6 3 12.566370614359172
NaN
NaN
NaN
NaN
NaN
NaN
```

2023-09-13 20:00 UTC, ShaikMoAbdullah commented on Week-4/assignment-6.3/script.js
I am getting true here. Maybe we can double-check

<img width="1440" alt="Screenshot 2023-09-14 at 1 29 39 AM" src="https://github.com/pesto-students/p13-nishant-naithani-ShaikMoAbdullah/assets/52700318/aaf088a5-b98f-4b69-9ebc-c6126f3e5156">

2023-09-13 20:18 UTC, ShaikMoAbdullah commented on Week-4/assignment-8.2/script.js
Fixed this. The problem was that the private variables were not inherited from the parent class. To solve this, Created a method that would give us the private variable.

2023-09-14 17:29 UTC, NishantNaithani requested changes

2023-09-14 17:29 UTC, NishantNaithani commented on Week-4/assignment-6.3/script.js
But we cannot pass `PASSWORD` in any way, but this function is giving `true` which means it is a string password.

2023-09-14 18:23 UTC, ShaikMoAbdullah commented on Week-4/assignment-6.3/script.js
The LMS had only mentioned that the input cannot be a password. Should I also consider the uppercase PASSWORD?

2023-12-12 18:20 UTC, merged